# Generated by Django 4.2.4 on 2023-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(default="Temporary not filled", max_length=100),
        ),
    ]
