# Generated by Django 4.2.4 on 2023-08-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0004_item_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="color",
        ),
        migrations.AddField(
            model_name="item",
            name="colors",
            field=models.ManyToManyField(to="MainApp.color"),
        ),
    ]
